import { StyleSheet } from 'react-native';
import { colors, componentStyles, layout, radius, spacing, typography } from '../utils/theme';

export const styles = StyleSheet.create({
  root: { flex: 1 },
  listFlex: { flex: 1 },
  list: { paddingHorizontal: layout.pagePaddingX, paddingTop: layout.pagePaddingTop, paddingBottom: layout.pagePaddingBottom },
  emptyList: { flexGrow: 1, paddingHorizontal: layout.pagePaddingX, paddingTop: layout.pagePaddingTop, paddingBottom: layout.pagePaddingBottom },
  header: { paddingBottom: spacing.md },
  summary: { ...typography.helper, marginBottom: spacing.md },

  viewRow: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.md },
  modeRow: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.md },
  toggle: {
    flex: 1,
    ...componentStyles.pill,
  },
  toggleSelected: { ...componentStyles.pillSelected, borderColor: colors.text },
  toggleText: { ...typography.smallLabel },

  navRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: spacing.md },
  navTitle: { ...typography.sectionTitle },
  navBtn: {
    width: 40,
    height: 40,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  legendRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, marginBottom: spacing.md },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  legendSwatchSolid: { width: 14, height: 14, borderRadius: 7, backgroundColor: colors.text },
  legendSwatchDashed: { width: 14, height: 14, borderRadius: 7, borderWidth: 2, borderColor: colors.text, borderStyle: 'dashed' },
  legendText: { ...typography.helper },

  calWeekdays: { flexDirection: 'row', marginBottom: 8 },
  calWDay: { flex: 1, ...typography.labelCaps, textTransform: 'none', textAlign: 'center' },
  calGrid: { gap: 8, marginBottom: spacing.md },
  calWeek: { flexDirection: 'row', gap: 8 },
  calCell: {
    flex: 1,
    aspectRatio: 1,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calDayText: { fontSize: 13, fontWeight: '800', color: colors.text },
  calMarkedSolid: { backgroundColor: colors.text, borderColor: colors.text },
  calMarkedSolidText: { color: colors.surface },
  calMarkedPredicted: { borderWidth: 2, borderColor: colors.text, borderStyle: 'dashed' },

  yearGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md },
  miniMonth: {
    width: '47%',
    ...componentStyles.card,
  },
  miniTitle: { fontSize: 12, fontWeight: '900', color: colors.text, marginBottom: 8 },
  miniWeekdays: { flexDirection: 'row', marginBottom: 6 },
  miniWDay: { flex: 1, fontSize: 9, fontWeight: '800', color: colors.textTertiary, textAlign: 'center' },
  miniGrid: { gap: 4 },
  miniWeek: { flexDirection: 'row', gap: 4 },
  miniCell: {
    flex: 1,
    aspectRatio: 1,
    borderRadius: 6,
    backgroundColor: 'rgba(17, 17, 17, 0.03)',
    borderWidth: 1,
    borderColor: 'rgba(17, 17, 17, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  miniDayText: { fontSize: 9, fontWeight: '800', color: colors.text, opacity: 0.75 },
  miniSolid: { backgroundColor: colors.text, borderColor: colors.text },
  miniSolidText: { color: colors.surface, opacity: 1 },
  miniPredicted: { borderWidth: 2, borderColor: colors.text, borderStyle: 'dashed', backgroundColor: 'transparent' },

  card: {
    ...componentStyles.card,
    marginBottom: spacing.md,
  },
  cardTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  cardTopText: { flex: 1, minWidth: 0 },
  cardActions: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  editHit: {
    width: 40,
    height: 40,
    borderRadius: radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.border,
  },
  rangeTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.text,
    letterSpacing: -0.2,
    lineHeight: 24,
  },
  duration: {
    marginTop: 6,
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
    lineHeight: 20,
    opacity: 0.72,
  },
  flowRow: { marginTop: spacing.sm, flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  flowLabel: { fontSize: 13, fontWeight: '700', color: colors.textTertiary },
  flowDots: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  flowDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 1.5,
    borderColor: 'rgba(17, 17, 17, 0.25)',
  },
  notes: { marginTop: spacing.sm, ...typography.body, lineHeight: 22 },
  meta: { marginTop: spacing.md, ...typography.helper },
  empty: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: spacing.xl },
  emptyIcon: { marginBottom: spacing.md },
  emptyTitle: { fontSize: 18, fontWeight: '700', color: colors.text, marginBottom: spacing.sm },
  emptyBody: { ...typography.body, textAlign: 'center' },
});
