import { StyleSheet } from 'react-native';
import { palette } from '../utils/palette';
import { spacing } from '../utils/theme';

const cardBorder = {
  borderWidth: StyleSheet.hairlineWidth,
  borderColor: 'rgba(17, 17, 17, 0.1)',
} as const;

export const styles = StyleSheet.create({
  root: { flex: 1 },
  listFlex: { flex: 1 },
  list: { padding: spacing.lg, paddingBottom: spacing.xl * 2 },
  emptyList: { flexGrow: 1, padding: spacing.lg, paddingBottom: spacing.xl * 2 },
  header: { paddingBottom: spacing.md },
  summary: { fontSize: 14, lineHeight: 20, color: palette.black, opacity: 0.8, marginBottom: spacing.md },

  viewRow: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.md },
  modeRow: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.md },
  sortRow: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.md },
  toggle: {
    flex: 1,
    paddingVertical: spacing.sm,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.white,
    ...cardBorder,
    borderWidth: 2,
    borderColor: 'rgba(17, 17, 17, 0.12)',
  },
  toggleSelected: { borderColor: palette.black },
  toggleText: { fontSize: 14, fontWeight: '700', color: palette.black },

  navRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: spacing.md },
  navTitle: { fontSize: 16, fontWeight: '900', color: palette.black, letterSpacing: -0.2 },
  navBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.white,
    ...cardBorder,
  },
  legendRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, marginBottom: spacing.md },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  legendSwatchSolid: { width: 14, height: 14, borderRadius: 7, backgroundColor: palette.black },
  legendSwatchDashed: { width: 14, height: 14, borderRadius: 7, borderWidth: 2, borderColor: palette.black, borderStyle: 'dashed' },
  legendText: { fontSize: 12, fontWeight: '700', color: palette.black, opacity: 0.75 },

  calWeekdays: { flexDirection: 'row', marginBottom: 8 },
  calWDay: { flex: 1, fontSize: 11, fontWeight: '800', color: palette.black, opacity: 0.6, textAlign: 'center' },
  calGrid: { gap: 8, marginBottom: spacing.md },
  calWeek: { flexDirection: 'row', gap: 8 },
  calCell: {
    flex: 1,
    aspectRatio: 1,
    borderRadius: 12,
    backgroundColor: palette.white,
    ...cardBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calDayText: { fontSize: 13, fontWeight: '800', color: palette.black },
  calMarkedSolid: { backgroundColor: palette.black, borderColor: palette.black },
  calMarkedSolidText: { color: palette.white },
  calMarkedPredicted: { borderWidth: 2, borderColor: palette.black, borderStyle: 'dashed' },

  yearGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md },
  miniMonth: {
    width: '47%',
    backgroundColor: palette.white,
    borderRadius: 16,
    padding: spacing.md,
    ...cardBorder,
  },
  miniTitle: { fontSize: 12, fontWeight: '900', color: palette.black, marginBottom: 8 },
  miniWeekdays: { flexDirection: 'row', marginBottom: 6 },
  miniWDay: { flex: 1, fontSize: 9, fontWeight: '800', color: palette.black, opacity: 0.55, textAlign: 'center' },
  miniGrid: { gap: 4 },
  miniWeek: { flexDirection: 'row', gap: 4 },
  miniCell: {
    flex: 1,
    aspectRatio: 1,
    borderRadius: 6,
    backgroundColor: 'rgba(17, 17, 17, 0.03)',
    borderWidth: 1,
    borderColor: 'rgba(17, 17, 17, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  miniDayText: { fontSize: 9, fontWeight: '800', color: palette.black, opacity: 0.75 },
  miniSolid: { backgroundColor: palette.black, borderColor: palette.black },
  miniSolidText: { color: palette.white, opacity: 1 },
  miniPredicted: { borderWidth: 2, borderColor: palette.black, borderStyle: 'dashed', backgroundColor: 'transparent' },

  card: {
    backgroundColor: palette.white,
    borderRadius: 16,
    padding: spacing.md,
    marginBottom: spacing.md,
    ...cardBorder,
  },
  cardTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  cardTopText: { flex: 1, minWidth: 0 },
  cardActions: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  editHit: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.white,
    ...cardBorder,
  },
  rangeTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: palette.black,
    letterSpacing: -0.2,
    lineHeight: 24,
  },
  duration: {
    marginTop: 6,
    fontSize: 14,
    fontWeight: '600',
    color: palette.black,
    lineHeight: 20,
    opacity: 0.72,
  },
  flowRow: { marginTop: spacing.sm, flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  flowLabel: { fontSize: 13, fontWeight: '700', color: palette.black, opacity: 0.75 },
  flowDots: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  flowDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 1.5,
    borderColor: 'rgba(17, 17, 17, 0.25)',
  },
  notes: { marginTop: spacing.sm, fontSize: 15, lineHeight: 22, color: palette.black },
  meta: { marginTop: spacing.md, fontSize: 12, color: palette.black, opacity: 0.75, lineHeight: 16 },
  empty: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: spacing.xl },
  emptyIcon: { marginBottom: spacing.md },
  emptyTitle: { fontSize: 18, fontWeight: '700', color: palette.black, marginBottom: spacing.sm },
  emptyBody: { fontSize: 15, lineHeight: 22, color: palette.black, textAlign: 'center' },
});
