import { Platform, StyleSheet } from 'react-native';
import { palette } from '../utils/palette';
import { spacing } from '../utils/theme';

const cardBorder = {
  borderWidth: StyleSheet.hairlineWidth,
  borderColor: 'rgba(17, 17, 17, 0.1)',
} as const;

export const styles = StyleSheet.create({
  root: { flex: 1 },
  content: { padding: spacing.lg, paddingBottom: spacing.xl * 2 },
  body: { marginTop: 4, fontSize: 15, lineHeight: 22, color: palette.black },
  section: {
    marginTop: spacing.lg,
    fontSize: 11,
    fontWeight: '700',
    color: palette.black,
    textTransform: 'uppercase',
    letterSpacing: 0.7,
    marginBottom: spacing.sm,
  },
  card: {
    backgroundColor: palette.white,
    borderRadius: 16,
    padding: spacing.md,
    ...cardBorder,
  },
  row: { marginBottom: spacing.md },
  itemTitle: { fontSize: 15, fontWeight: '700', color: palette.black, lineHeight: 21 },
  desc: { marginTop: 4, fontSize: 14, lineHeight: 20, color: palette.black },
  bold: { fontWeight: '700', color: palette.black },
  footer: { marginTop: spacing.lg, fontSize: 13, color: palette.black, textAlign: 'center', lineHeight: 18 },

  exportCard: {
    backgroundColor: palette.white,
    borderRadius: 16,
    padding: spacing.md,
    ...cardBorder,
  },
  fieldLabel: {
    marginTop: spacing.sm,
    marginBottom: spacing.xs,
    fontSize: 11,
    fontWeight: '700',
    color: palette.black,
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  fieldLabelFirst: {
    marginTop: 0,
    marginBottom: spacing.xs,
    fontSize: 11,
    fontWeight: '700',
    color: palette.black,
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  input: {
    backgroundColor: palette.white,
    ...cardBorder,
    borderRadius: 12,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    fontSize: 16,
    color: palette.black,
  },
  helper: {
    marginTop: spacing.xs,
    fontSize: 12,
    lineHeight: 17,
    color: palette.black,
    opacity: 0.8,
  },
  error: {
    marginTop: spacing.xs,
    fontSize: 12,
    lineHeight: 17,
    color: palette.black,
    opacity: 0.9,
  },
  presetsGrid: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  presetChip: {
    flex: 1,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: 999,
    backgroundColor: palette.white,
    ...cardBorder,
    borderWidth: 2,
    borderColor: 'rgba(17, 17, 17, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  presetChipText: {
    fontSize: 14,
    fontWeight: '600',
    color: palette.black,
  },
  formatRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.sm,
    flexWrap: 'wrap',
  },
  formatChip: {
    flexGrow: 1,
    flexBasis: 0,
    paddingVertical: spacing.sm,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.white,
    ...cardBorder,
  },
  formatChipSelected: {
    borderWidth: 2,
    borderColor: palette.black,
  },
  formatChipLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: palette.black,
  },
  exportButton: {
    marginTop: spacing.lg,
    paddingVertical: spacing.md,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  exportButtonPressed: { opacity: 0.92 },
  exportLabel: { color: palette.black, fontSize: 16, fontWeight: '700' },

  pathBox: {
    marginTop: spacing.md,
    padding: spacing.sm,
    borderRadius: 12,
    backgroundColor: 'rgba(17, 17, 17, 0.04)',
    ...cardBorder,
  },
  pathLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: palette.black,
    marginBottom: 4,
  },
  pathText: {
    fontSize: 12,
    lineHeight: 17,
    color: palette.black,
    fontFamily: Platform.select({ ios: 'Menlo', android: 'monospace', default: 'monospace' }),
  },
  copyRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  copyPill: {
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: 12,
    backgroundColor: palette.white,
    ...cardBorder,
  },
  copyPillLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: palette.black,
  },
  lastExportNote: {
    marginTop: spacing.md,
    fontSize: 14,
    lineHeight: 20,
    color: palette.black,
  },
  technical: {
    marginTop: spacing.xs,
    fontSize: 12,
    lineHeight: 17,
    color: palette.black,
    opacity: 0.85,
  },
  inlineFieldLabel: {
    marginTop: spacing.lg,
    marginBottom: spacing.sm,
    fontSize: 11,
    fontWeight: '700',
    color: palette.black,
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },

  dangerCard: {
    backgroundColor: palette.white,
    borderRadius: 16,
    padding: spacing.md,
    ...cardBorder,
  },
  dangerButton: {
    marginTop: spacing.md,
    paddingVertical: spacing.md,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    backgroundColor: palette.black,
  },
  dangerButtonLabel: { color: palette.white, fontSize: 16, fontWeight: '800' },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(17, 17, 17, 0.38)',
    padding: spacing.lg,
    justifyContent: 'center',
  },
  modalCard: {
    backgroundColor: palette.white,
    borderRadius: 18,
    padding: spacing.lg,
    ...cardBorder,
  },
  modalTitle: { fontSize: 18, fontWeight: '900', color: palette.black },
  modalBody: { marginTop: spacing.sm, fontSize: 14, lineHeight: 20, color: palette.black, opacity: 0.88 },
  modalActions: { marginTop: spacing.lg, flexDirection: 'row', gap: spacing.sm },
  modalButton: {
    flex: 1,
    paddingVertical: spacing.sm,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(17, 17, 17, 0.06)',
    ...cardBorder,
  },
  modalButtonPrimary: {
    flex: 1,
    paddingVertical: spacing.sm,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.black,
  },
  modalButtonLabel: { fontSize: 15, fontWeight: '800', color: palette.black },
  modalButtonLabelPrimary: { fontSize: 15, fontWeight: '900', color: palette.white },
});
